### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by conan-2** [CatAnd-Dog/wechat_gpt#1]
感谢大佬，请问是否可增加通过环境变量修改默认模型和默认返回提示

**Comment by CatAnd-Dog** [comment]
好了，重新拉更新就好了

![1715514454233](https://img.52cn.me/i/2024/05/12/w7eust.jpg)

# 默认模型
DEFAULT_MODEL=
# 默认回复
DEFAULT_REPLY=
